/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appForms;

import java.awt.Color;

/**
 *
 * @author Ibrahim Jaber
 * This form holds the conversion history of the words that has been converted in the convert Morse form 
 * in which the user can see all the words that has been converted and the date the conversion was made on
 */
public class conversionHistory extends javax.swing.JFrame {

    /**
     * Creates new form conversionHistory
     */
    public conversionHistory() {
        initComponents();
        project_classes.DBLogic dl = new project_classes.DBLogic();//Initializing a DBLogic Object
        dl.GetConnection();//Getting the connection
        dl.populateConversionHistory(conversionHistoryTbl);//we populate the table conversionHistoryTbl by calling DBLogic member method populateConversionHistory
        this.setTitle("Conversion History");//setting the title of the form
        this.setResizable(false);//Setting the resizable option to false
        getContentPane().setBackground(Color.decode("#005580"));//changing main panle background 
        mainPanel.setBackground(Color.decode("#005580"));//changing the secondary panle back-ground
        conversionHistoryTbl.setBackground(Color.decode("#33D1B9"));//setting the back-gounrd of the JTable conversionHistoryTbl
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conversionHistoryTbl = new javax.swing.JTable();
        convertMrsCBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        resourcesBtn = new javax.swing.JButton();
        morsealphabetandMachine = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conversionHistoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "English word", "Morse word", "Conversion Date"
            }
        ));
        jScrollPane1.setViewportView(conversionHistoryTbl);

        convertMrsCBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        convertMrsCBtn.setText("Convert Morse code");
        convertMrsCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertMrsCBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        resourcesBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resourcesBtn.setText("Resources");
        resourcesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesBtnActionPerformed(evt);
            }
        });

        morsealphabetandMachine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        morsealphabetandMachine.setText("Morse Alphabet and Machine");
        morsealphabetandMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morsealphabetandMachineActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Conversion History ");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(morsealphabetandMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resourcesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(convertMrsCBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(convertMrsCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(resourcesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(morsealphabetandMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Main Menu form and hide the current form
     */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new morseHistory().setVisible(true);
    }//GEN-LAST:event_mainMenuBtnActionPerformed
    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Convert morse code and hide the current form
     */
    private void convertMrsCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertMrsCBtnActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new convertCode().setVisible(true);
    }//GEN-LAST:event_convertMrsCBtnActionPerformed
    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Resources form and hide the current form
     */
    private void resourcesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Resources().setVisible(true);
    }//GEN-LAST:event_resourcesBtnActionPerformed
    /**
     * 
     * 
     * @param evt 
     * this button when it's clicked it will open the Morse Alphabet examples and machine form and hide the current form
     */
    private void morsealphabetandMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morsealphabetandMachineActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new morseAlphabet().setVisible(true);
    }//GEN-LAST:event_morsealphabetandMachineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversionHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable conversionHistoryTbl;
    private javax.swing.JButton convertMrsCBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton morsealphabetandMachine;
    private javax.swing.JButton resourcesBtn;
    // End of variables declaration//GEN-END:variables
}
