/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appForms;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ibrahim Jaber
 * This for has the convert words to Morse code part
 * the user will be able to insert words and can see there conversion in Morse
 * then the results will be saved in CovnersionHistory Table in the Database
 * 
 */
public class convertCode extends javax.swing.JFrame {

    /**
     * Creates new form convertCode
     */
    public convertCode() {
        initComponents();
        this.setTitle("Morse Code Convertor");//setting the title of the form
        this.setResizable(false);//setting the resizable option to false
        getContentPane().setBackground(Color.decode("#005580"));//changing the main panle back ground color
        panelconvert.setBackground(Color.decode("#005580"));//changing the secondry panle color
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelconvert = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        convertBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        englishWord = new javax.swing.JTextArea();
        MorseEnglishVal = new javax.swing.JLabel();
        mainMenuBtn = new javax.swing.JButton();
        MorseAlphMachine = new javax.swing.JButton();
        demonLbl = new javax.swing.JLabel();
        resourcesBtn = new javax.swing.JButton();
        conversionHistoryBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLbl.setText("MORSE CODE WORD CONVERTER");

        convertBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        englishWord.setColumns(20);
        englishWord.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        englishWord.setRows(5);
        jScrollPane1.setViewportView(englishWord);

        MorseEnglishVal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MorseEnglishVal.setForeground(new java.awt.Color(0, 255, 51));

        mainMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainMenuBtn.setText("Main menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        MorseAlphMachine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MorseAlphMachine.setText("Morse Code Alphabet & mahcine sample");
        MorseAlphMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorseAlphMachineActionPerformed(evt);
            }
        });

        demonLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        demonLbl.setText("Enter a word to encrypt");

        resourcesBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resourcesBtn.setText("Resources");
        resourcesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesBtnActionPerformed(evt);
            }
        });

        conversionHistoryBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conversionHistoryBtn.setText("Conversion History");
        conversionHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionHistoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelconvertLayout = new javax.swing.GroupLayout(panelconvert);
        panelconvert.setLayout(panelconvertLayout);
        panelconvertLayout.setHorizontalGroup(
            panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconvertLayout.createSequentialGroup()
                .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelconvertLayout.createSequentialGroup()
                                .addComponent(demonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelconvertLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(titleLbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconvertLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelconvertLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MorseEnglishVal, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addComponent(resourcesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MorseAlphMachine)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conversionHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        panelconvertLayout.setVerticalGroup(
            panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelconvertLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(demonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conversionHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(MorseAlphMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelconvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(resourcesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelconvertLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(MorseEnglishVal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(panelconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 5, 1110, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/morseCodeFormConverter.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 536, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     * in this event listening function
     * we instantiate an object of DBlogic class 
     * then we instantiate an object of MorseCode class
     * we convert the english word to morse by calling morseCode member method
     * then we save the result in our database table 
     * as show below
     */
    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        // TODO add your handling code here:
        project_classes.DBLogic db = new project_classes.DBLogic();//Intalizing DBLogic object
        db.GetConnection();//Getting connection
        String MorseVal;
        String englishW = this.englishWord.getText();//getting the texst value from the text field
        project_classes.morseCode morseCode = new project_classes.morseCode();//Intalizing morseCode object
        if(englishW.isEmpty()){//we validate that the text feild is not empty if so we provide a pop mesasage to the user
            JOptionPane.showMessageDialog(null, "Please enter a value to encrypt");
        }else{
            MorseVal = morseCode.convertCode(englishW);//we convert the word by calling convertCode member method form morseCode class
            JOptionPane.showMessageDialog(null, "This word : "+englishW + " Will be converted to Morse press OK to continue.");//we show a successfull pop message to the user
            MorseEnglishVal.setText( englishW + ": " +MorseVal);//set the text to our lable
            db.insertConversionHistory(englishW, MorseVal);//insert the vlaue to our DBLogic class memebr method in order to save the resultsin our Table
            
        }

    }//GEN-LAST:event_convertBtnActionPerformed
    /**
     * 
     * 
     * @param evt 
     * this button when it's clicked it will open the Main menu form and hide the current form
     */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new morseHistory().setVisible(true);
    }//GEN-LAST:event_mainMenuBtnActionPerformed
    /**
     * 
     * @param evt
     * this button when it's clicked it will open the MorseLAphabet examples and machine form and hide the current form
     */
    private void MorseAlphMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorseAlphMachineActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new morseAlphabet().setVisible(true);
    }//GEN-LAST:event_MorseAlphMachineActionPerformed
    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Resources form and hide the current form
     */
    private void resourcesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesBtnActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       new Resources().setVisible(true);
    }//GEN-LAST:event_resourcesBtnActionPerformed
   /**
    * 
    * @param evt 
    * this button when it's clicked it will open the conversionHistory form and hide the current form
    */
    private void conversionHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionHistoryBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new conversionHistory().setVisible(true);
    }//GEN-LAST:event_conversionHistoryBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MorseAlphMachine;
    private javax.swing.JLabel MorseEnglishVal;
    private javax.swing.JButton conversionHistoryBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JLabel demonLbl;
    private javax.swing.JTextArea englishWord;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JPanel panelconvert;
    private javax.swing.JButton resourcesBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
