/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appForms;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Ibrahim Jaber
 * This Form holds the Resources of Morse related information like video articles and educational resources. 
 */
public class Resources extends javax.swing.JFrame {

    /**
     * Creates new form Resources
     */ 
    public Resources() {
        initComponents();
        this.setTitle("Morse Code Resources");//setting the title of the form
        this.setResizable(false);//setting the resizable option to false
        panelResources.setBackground(Color.decode("#005580"));//changing the panle back-ground color
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResources = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        morseWikiBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        watchMorseBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        leanrMorseBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        convertBtn = new javax.swing.JButton();
        MorseExampleBtn = new javax.swing.JButton();
        conversionHistoryBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("What is Morse Code? Click the Image Below.");

        morseWikiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        morseWikiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morseWikiBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("                 Video Explanation");

        watchMorseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlayButton.png"))); // NOI18N
        watchMorseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchMorseBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Learn Morse Code?");

        leanrMorseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/learnMorse.png"))); // NOI18N
        leanrMorseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leanrMorseBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainMenuBtn.setText("Main menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        convertBtn.setText("Convert Morse Code");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        MorseExampleBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MorseExampleBtn.setText("Morse Alphabet and Machine");
        MorseExampleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorseExampleBtnActionPerformed(evt);
            }
        });

        conversionHistoryBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conversionHistoryBtn.setText("Conversion History");
        conversionHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversionHistoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResourcesLayout = new javax.swing.GroupLayout(panelResources);
        panelResources.setLayout(panelResourcesLayout);
        panelResourcesLayout.setHorizontalGroup(
            panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResourcesLayout.createSequentialGroup()
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(morseWikiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)
                        .addComponent(watchMorseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(leanrMorseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conversionHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MorseExampleBtn)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResourcesLayout.setVerticalGroup(
            panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResourcesLayout.createSequentialGroup()
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(watchMorseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morseWikiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MorseExampleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(conversionHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(leanrMorseBtn))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResources, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResources, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     * once this button is clicked it will open an outside resource through a link 
     * it's encapsulated in try and catch bloc to handle any possible exceptions 
     */
    private void morseWikiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morseWikiBtnActionPerformed
        // TODO add your handling code here:
         try { 
        Desktop.getDesktop().browse(new URI("https://en.wikipedia.org/wiki/Morse_code"));
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
     }
    }//GEN-LAST:event_morseWikiBtnActionPerformed
    /**
     * 
     * @param evt 
     * nce this button is clicked it will open an outside resource through a link 
     * it's encapsulated in try and catch bloc to handle any possible exceptions 
     */
    private void watchMorseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchMorseBtnActionPerformed
        // TODO add your handling code here:
         try { 
        Desktop.getDesktop().browse(new URI("https://youtu.be/iy8BaMs_JuI"));
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
     }
    }//GEN-LAST:event_watchMorseBtnActionPerformed
    /**
     * 
     * @param evt
     * nce this button is clicked it will open an outside resource through a link 
     * it's encapsulated in try and catch bloc to handle any possible exceptions 
     */
    private void leanrMorseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leanrMorseBtnActionPerformed
        // TODO add your handling code here:
                 try { 
        Desktop.getDesktop().browse(new URI("https://morse.withgoogle.com/learn/"));
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
     }
    }//GEN-LAST:event_leanrMorseBtnActionPerformed

    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Convert Morse Code form and hide the current form
     */
    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new convertCode().setVisible(true);
    }//GEN-LAST:event_convertBtnActionPerformed
    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Morse Alphabet examples and machine form and hide the current form
     */
    private void MorseExampleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorseExampleBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new morseAlphabet().setVisible(true);
    }//GEN-LAST:event_MorseExampleBtnActionPerformed
    /**
     * 
     * @param evt 
     * this button when it's clicked it will open the Main Menu form and hide the current form
     */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new morseHistory().setVisible(true);
    }//GEN-LAST:event_mainMenuBtnActionPerformed
    /**
     * 
     * @param evt 
     * this button when it's clicked it will open theConversion History form and hide the current form
     */
    private void conversionHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversionHistoryBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new conversionHistory().setVisible(true);
    }//GEN-LAST:event_conversionHistoryBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resources().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MorseExampleBtn;
    private javax.swing.JButton conversionHistoryBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton leanrMorseBtn;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton morseWikiBtn;
    private javax.swing.JPanel panelResources;
    private javax.swing.JButton watchMorseBtn;
    // End of variables declaration//GEN-END:variables
}
